#!/usr/bin/with-contenv bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-warning}
UMASK=${UMASK:-022}

umask "$UMASK"

exec \
	s6-setuidgid abc /usr/bin/deluge-web \
	-c /config --loglevel=${DELUGE_LOGLEVEL}
