#!/usr/bin/with-contenv bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-info}
UMASK=${UMASK:-022}

umask "$UMASK"

exec \
	s6-setuidgid abc /usr/bin/deluged -c /config \
	-d --loglevel=${DELUGE_LOGLEVEL} -l /config/deluged.log
